relaxed_adj = {
    "Addis Ababa": ["Ambo", "Adama", "Debre Birhan"],
    "Ambo": ["Addis Ababa", "Nekemte", "Wolkite"],
    "Adama": ["Addis Ababa", "Batu", "Assella", "Matahara"],
    "Debre Birhan": ["Addis Ababa"],
    "Nekemte": ["Ambo", "Gimbi", "Bedelle"],
    "Gimbi": ["Nekemte", "Dembi Dollo"],
    "Dembi Dollo": ["Gimbi", "Gambella"],
    "Gambella": ["Dembi Dollo", "Gore"],
    "Gore": ["Gambella", "Tepi", "Bedelle"],
    "Bedelle": ["Gore", "Nekemte", "Jimma"],
    "Jimma": ["Bedelle", "Wolkite", "Bonga"],
    "Wolkite": ["Ambo", "Jimma", "Worabe"],
    "Buta Jirra": ["Batu", "Worabe"],
    "Batu": ["Adama", "Buta Jirra", "Shashemene"],
    "Assella": ["Adama", "Assasa"],
    "Matahara": ["Adama", "Awash"],
    "Awash": ["Matahara", "Chiro"],
    "Chiro": ["Awash", "Dire Dawa"],
    "Dire Dawa": ["Chiro", "Harar"],
    "Harar": ["Dire Dawa", "Babile"],
    "Babile": ["Harar", "Jigjiga"],
    "Jigjiga": ["Babile", "Dega Habur"],
    "Dega Habur": ["Jigjiga", "Kebri Dehar"],
    "Kebri Dehar": ["Dega Habur", "Gode", "Werder"],
    "Werder": ["Kebri Dehar"],
    "Gode": ["Kebri Dehar"],
    "Tepi": ["Gore", "Mezan Teferi", "Bonga"],
    "Bonga": ["Tepi", "Jimma", "Dawro"],
    "Mezan Teferi": ["Tepi"],
    "Dawro": ["Bonga", "Wolaita Sodo"],
    "Wolaita Sodo": ["Dawro", "Hossana", "Arba Minch"],
    "Hossana": ["Wolaita Sodo", "Worabe"],
    "Worabe": ["Hossana", "Wolkite", "Buta Jirra"],
    "Arba Minch": ["Wolaita Sodo", "Konso"],
    "Konso": ["Arba Minch", "Yabello"],
    "Yabello": ["Konso", "Moyale", "Bule Hora"],
    "Bule Hora": ["Yabello", "Dilla"],
    "Dilla": ["Bule Hora", "Hawassa"],
    "Hawassa": ["Dilla", "Shashemene"],
    "Shashemene": ["Hawassa", "Batu", "Dodolla"],
    "Dodolla": ["Shashemene", "Assasa", "Bale"],
    "Assasa": ["Dodolla", "Assella"],
    "Bale": ["Dodolla", "Goba", "Sof Oumer", "Liben"],
    "Goba": ["Bale", "Sof Oumer", "Dega Habur"],
    "Sof Oumer": ["Goba", "Bale", "Gode"],
    "Liben": ["Bale"]
}
city_coordinates = {
    "Addis Ababa": (0, 0), 
    "Adama": (1, -1), 
    "Ambo": (-1, 0),
    "Debre Birhan": (0.5, 1), 
    "Nekemte": (-2, 0.5), 
    "Jimma": (-1.5, -1.5),
    "Wolkite": (-0.8, -0.8), 
    "Buta Jirra": (0.2, -1.2), 
    "Batu": (0.8, -1.5),
    "Shashemene": (1, -2.5), 
    "Hawassa": (1, -3.5), 
    "Dilla": (1, -4.5),

    "Konso": (0.5, -5.5),
    "Bule Hora": (0.8, -6),
    "Yabello": (1, -6.5),
    "Moyale": (1, -7),

    "Assella": (1.5, -0.5),
    "Assasa": (1.5, -1.5),
    "Dodolla": (1.5, -2.2),

    "Matahara": (2, -0.5),
    "Awash": (2.5, 0),
    "Chiro": (3, 0),
    "Dire Dawa": (3.5, 0),
    "Harar": (4, 0.5),
    "Babile": (4, 0),
    "Jigjiga": (4.5, 0),

    "Dega Habur": (4.5, -1),
    "Kebri Dehar": (4.5, -2),
    "Werder": (5, -2),

    "Gode": (3.5, -2.5),

    "Bale": (2.5, -3),
    "Goba": (3, -3),
    "Sof Oumer": (3.5, -3),
    "Liben": (2.5, -4),

    "Lalibela": (0, 4), 
    "Gondar": (-2, 4)
}
