graph1 = {
    "Humera": ["Shire", "Gondar"],
    "Shire": ["Humera", "Debarke","Axum"],
    "Axum": ["Shire", "Adwa"],
    "Adwa": ["Axum", "Mekelle", "Adigrat"],
    "Debarke": ["Humera","Shire", "Gondar"],
    "Gondar": ["Debarke", "Metema", "Azezo","Humera"],
    "Metema": ["Azezo", "Gondar"],
    "Azezo": ["Gondar", "Bahir Dar","Metema"],
    "Bahir Dar": ["Azezo", "Debre Tabor", "Metekel", "Injibara", "Finote Selam"],
    "Mekelle":["Adwa","Adigrat","Alamata","Sekota"],
    "Assosa": ["Metekel", "Dembi Dollo"],
    "Dembi Dollo": ["Assosa", "Gimbi", "Gambela"],
    "Gambela": ["Dembi Dollo","Gore"],
    "Gore": ["Bedelle","Tepi"],
    "Gimbi": ["Dembi Dollo", "Nekemte"],
    "Nekemte": ["Gimbi", "Bedelle", "Ambo"],
    "Bedelle": ["Nekemte", "Gore","Jimma"],
    "Jimma": ["Bedelle", "Bonga", "Wolkite"],
    "Bonga": ["Jimma", "Tepi", "Dawro","Mezan Teferi"],
    "Tepi": ["Bonga","Mezan Teferi" "Gore"],
    "Gore": ["Tepi", "Gambela","Bedelle"],
    "Dawro": ["Bonga", "Wolaita Sodo"],
    "Wolaita Sodo": ["Dawro", "Hossana", "Arba Minch"],
    "Hossana": ["Wolaita Sodo", "Worabe","Shashemene"],
    "Worabe": ["Hossana", "Butajira","Wolkite"],
    "Butajira": ["Worabe", "Batu"],
    "Batu": ["Butajira", "Adama","Shashemene"],
    "Adama": ["Batu", "Addis Ababa", "Assella", "Matahara"],
    "Addis Ababa": ["Adama", "Ambo", "Debre Birhan"],
    "Ambo": ["Addis Ababa", "Wolkite", "Nekemte"],
    "Wolkite": ["Ambo", "Jimma","Worabe"],
    "Hawassa": [ "Dilla", "Shashemene"],
    "Dilla": ["Hawassa", "Bule Hora"],
    "Mezan Teferi":["Bonga","Basketo","Tepi"],
    "Basketo": ["Arba Minch", "Bench Maji","Mezan Teferi","Dawro"],
    "Bule Hora": ["Dilla", "Yabello"],
    "Yabello": ["Bule Hora", "Moyale", "Konso"],
    "Moyale": ["Yabello"],
    "Konso": ["Yabello", "Arba Minch"],
    "Bench Maji": ["Basketo"],

    "Debre Tabor": ["Bahir Dar", "Lalibela"],
    "Lalibela": ["Debre Tabor", "Woldia","Sekota"],
    "Woldia": ["Lalibela", "Dessie", "Alamata","Samara"],
    "Dessie": ["Woldia", "Kemise"],
    "Kemise": ["Dessie", "Debre Sina"],
    "Debre Sina": ["Kemise", "Debre Birhan","Debre Markos"],
    "Debre Birhan": ["Debre Sina", "Addis Ababa"],
    "Debre Markos": ["Debre Sina", "Finote Selam"],

    "Sekota": ["Mekelle", "Lalibela","Alamata"],
    "Alamata": ["Mekelle", "Woldia", "Sekota","Samara"],
    "Samara": ["Alamata", "Gabi Rasu", "Fanti Rasu","Woldia","Alamata"],
    "Fanti Rasu": ["Samara", "Kilbet Rasu"],
    "Kilbet Rasu": ["Fanti Rasu"],

    "Gabi Rasu": ["Samara", "Awash"],
    "Awash": ["Gabi Rasu", "Chiro", "Matahara"],
    "Chiro": ["Awash", "Dire Dawa"],
    "Dire Dawa": ["Chiro", "Harar"],
    "Harar": ["Dire Dawa", "Babile"],
    "Babile": ["Harar", "Jigjiga"],
    "Jigjiga": ["Babile", "Dega Habur"],
    "Dega Habur": ["Jigjiga", "Kebri Dehar","Goba"],
    "Goba": ["Dega Habur","Bale","Sof Oumer"],
    "Kebri Dehar": ["Dega Habur", "Gode", "Werder","Sof Oumer"],
    "Werder": ["Kebri Dehar"],
    "Gode": ["Kebri Dehar", "Dollo"],
    "Dollo": ["Gode"],

    "Assella": ["Adama", "Assasa"],
    "Assasa": ["Assella", "Dodolla"],
    "Dodolla": ["Assasa", "Bale","Shashemene"],
    "Bale": ["Dodolla", "Sof Oumer", "Liben","Goba"],
    "Liben": ["Bale"],
    "Sof Oumer": ["Bale", "Kebri Dehar","Goba"],

    "Shashemene": ["Hawassa", "Hossana","Batu","Dodolla"]
}
